### ISSUE TITLE
How the calendar app work ?

### ISSUE THREAD

**Issue by mrsolarius** [adminmart/Adminmart-lite#1]
Hey !
I'Have download your Dashboard Admin, and it look realy good. The documentation is good but I don't have see anything about your calendar app. 
So can you explain how that work ?

Best Regards,
MrSolarius

**Comment by wrappixel** [comment]
@mrsolarius  Well, with admin mart used third party plugin called full-calendar, you can check their docs here in detail : https://fullcalendar.io/
